package wsaa.services.logincms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0 2023-05-09T19:28:43.327-03:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "LoginCMSService", wsdlLocation = "file:/C:/Users/camilo/Desktop/ar-expertizen-fe-jdk11/src/main/resources/LoginCms.wsdl", targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms")
public class LoginCMSService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("https://wsaahomo.afip.gov.ar/ws/services/LoginCms",
			"LoginCMSService");
	public final static QName LoginCms = new QName("https://wsaahomo.afip.gov.ar/ws/services/LoginCms", "LoginCms");
	static {
		URL url = null;
		try {
			url = new URL("file:/C:/Users/camilo/Desktop/ar-expertizen-fe-jdk11/src/main/resources/LoginCms.wsdl");
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(LoginCMSService.class.getName()).log(java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}",
					"file:/C:/Users/camilo/Desktop/ar-expertizen-fe-jdk11/src/main/resources/LoginCms.wsdl");
		}
		WSDL_LOCATION = url;
	}

	public LoginCMSService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public LoginCMSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public LoginCMSService() {
		super(WSDL_LOCATION, SERVICE);
	}

	public LoginCMSService(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	public LoginCMSService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	public LoginCMSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return returns LoginCMS
	 */
	@WebEndpoint(name = "LoginCms")
	public LoginCMS getLoginCms() {
		return super.getPort(LoginCms, LoginCMS.class);
	}

	/**
	 *
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *                 on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns LoginCMS
	 */
	@WebEndpoint(name = "LoginCms")
	public LoginCMS getLoginCms(WebServiceFeature... features) {
		return super.getPort(LoginCms, LoginCMS.class, features);
	}

}
