
package wsaa.services.logincms;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.5.0 2023-05-09T19:28:43.295-03:00
 * Generated source version: 3.5.0
 */

@WebFault(name = "fault", targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms")
public class LoginFault_Exception extends Exception {
	public static final long serialVersionUID = 1L;

	private wsaa.services.logincms.LoginFault faultInfo;

	public LoginFault_Exception() {
		super();
	}

	public LoginFault_Exception(String message) {
		super(message);
	}

	public LoginFault_Exception(String message, java.lang.Throwable cause) {
		super(message, cause);
	}

	public LoginFault_Exception(String message, wsaa.services.logincms.LoginFault fault) {
		super(message);
		this.faultInfo = fault;
	}

	public LoginFault_Exception(String message, wsaa.services.logincms.LoginFault fault,
			java.lang.Throwable cause) {
		super(message, cause);
		this.faultInfo = fault;
	}

	public wsaa.services.logincms.LoginFault getFaultInfo() {
		return this.faultInfo;
	}
}
