package wsaa.services.logincms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0 2023-05-09T19:28:43.320-03:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms", name = "LoginCMS")
@XmlSeeAlso({ ObjectFactory.class, wsaa.services.logincms.ObjectFactory.class })
public interface LoginCMS {

	@WebMethod
	@RequestWrapper(localName = "loginCms", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "gov.afip.desein.dvadac.sua.view.wsaa.LoginCms")
	@ResponseWrapper(localName = "loginCmsResponse", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "gov.afip.desein.dvadac.sua.view.wsaa.LoginCmsResponse")
	@WebResult(name = "loginCmsReturn", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov")
	public java.lang.String loginCms(

			@WebParam(name = "in0", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov") java.lang.String in0)
			throws LoginFault_Exception;
}
